name: Kernel Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu clang make libncurses5-dev bison flex libssl-dev

    - name: Configure Environment Variables
      run: |
        # Set up cross-compilation and paths
        export CROSS_COMPILE=aarch64-linux-androidkernel-
        export CC=$(pwd)/toolchain/clang13-main/bin/clang  # Path to Clang compiler
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export ARCH=arm64
        export ANDROID_MAJOR_VERSION=t
        export KCFLAGS=-w
        export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
      shell: bash

    - name: Clean Previous Builds
      run: |
        make clean && make mrproper
      shell: bash

    - name: Build Kernel Configuration
      run: |
        make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y physwizz_defconfig
      shell: bash

    - name: Build Kernel
      run: |
        make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y -j$(nproc)
      shell: bash

    - name: Copy Kernel Image
      run: |
        cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image
      shell: bash

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-Image
        path: $(pwd)/arch/arm64/boot/Image
